@baseUrl = https://api-bookmedial.rikudo.ci/api

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMjExYmRkMDgzM2U0MWIyOTRmM2ZiNmI4OTk1NWFjMGVhZmY4ZDQyYjE4ZWE5ZWRkMjdjMGUxNDY3ZmM2NzVmY2NlMzBlN2RhNzBlZDg1NzQiLCJpYXQiOjE2Mjk5NzMzMDUuNTA3MzQzLCJuYmYiOjE2Mjk5NzMzMDUuNTA3MzU2LCJleHAiOjE2NjE1MDkzMDUuNDg4NzYsInN1YiI6IjI5Iiwic2NvcGVzIjpbXX0.ei5guo_VL7KO2xtpZTYQSwwqShlcfvkswanw3NJu1iazsjT5vutZ-nV-v8a0Y2Q5G9b_htlzew-cR2KrsgVAHKuYuhWrwFz32q7iFk6Gzwp4frS6dNn2FdrmX1cm1d7x2kNY6U_pR5h0OdPTc6WyYFtV5vejcOAyRt92sIbr6a001sRonf431GQ1nuwDZ6FOsHqWVi77p-mkrK6Vc7C3x6mzhq8yx0PvZyVTOUa_pYuNmdq2z4jwvHRvfnnKbf7RCYo4zic0CE_gpViA7vxa6fIxZaXnvWpf5fom1rwRZuIFrDP9uoizzY8YFwQR_CTDnQovKiLEHbUbW7-7VpwhUWbGbpC21003wbE8R4lDDuXUj9JSqwUhHzzqWHmtlVRN1D4ltUcW-luydYC-cPbgtPupR4aOBfoiiOZHocC6tWw9jQS5b_QOAZd7j20djcRecJeEcFtxs-5QbDhqxciYgydxFHlJuO8s-Sbkivnmw3COj5Gk5WtNLZwPaOp37do2_60tIiIqGnCamluWe8W89wXpJ-mcpKrwyTdMhwUfvxui_0KL9Z18qsXF66i-nG4OFjeUN4AO6W3qXqhXoK5MRC0bduPGqFNvsF9wMKJgtfG84rOR6JPH9mKmfWiM6AoDedfJSqGgh9lllhrHdIbZOX7bBZz2eFapwi5QAchOwpM

POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "a.tissi@armeltissi.com",
  "password": "Password"
}

###

POST {{baseUrl}}/register
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUb2tlbiBBdXRoIiwiaWRQZXIiOiIxMTA4NTE0MCIsImNhdGVnIjoiVVNFUkVYVCIsImlzcyI6InZlb3MyIC0gUFJFUFJPRCAtIE9MRUEiLCJsYW5ndWFnZSI6IkYiLCJleHAiOjE2MjkzNzQwNDMsImlhdCI6MTYyOTM2MzI0M30.jNg22_Q63sr2_8vqQRtx8IqBgfo_YluvTawumO6ijKU

{
    "title": "Monsieur",
    "name": "Armel Tissi",
    "email": "tkjarmel@gmail.com",
    "password": "Password",
    "phone": "",
    "birth_date": "",
    "nationality": "",
    "gender": ""
}

###

POST {{baseUrl}}/social/login
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUb2tlbiBBdXRoIiwiaWRQZXIiOiIxMTA4NTE0MCIsImNhdGVnIjoiVVNFUkVYVCIsImlzcyI6InZlb3MyIC0gUFJFUFJPRCAtIE9MRUEiLCJsYW5ndWFnZSI6IkYiLCJleHAiOjE2MjkzNzQwNDMsImlhdCI6MTYyOTM2MzI0M30.jNg22_Q63sr2_8vqQRtx8IqBgfo_YluvTawumO6ijKU

{
    "title": "Monsieur",
    "name": "Armel Tissi",
    "email": "tkjarmel2@gmail.com",
    "password": "Armel1234",
    "phone": "",
    "birth_date": "",
    "nationality": "",
    "gender": ""
}

###

POST {{baseUrl}}/user/reset-password
Content-Type: application/json

{
    "email": "tkjarmel@gmail.com"
}

###

GET {{baseUrl}}/password/1234
Content-Type: application/json

###

POST {{baseUrl}}/password/update
Content-Type: application/json

{
    "email": "tkjarmel@gmail.com",
    "password": "Password"
}

###

GET {{baseUrl}}/properties/popular
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/properties
Content-Type: application/json
Authorization: Bearer {{token}}


###

GET {{baseUrl}}/properties/city/Abidjan
Content-Type: application/json
Authorization: Bearer {{token}}

###

POST {{baseUrl}}/properties/search?
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "location": "Abidjan", 
    "sejourStart": "27/08/2021", 
    "sejourEnd": "28/08/2021", 
    "totalPersons": 2, 
    "personsValue": "2 personnes", 
    "sejourValue": "27 août - 28 août", 
    "locationValue": "Grand-Bassam, Côte d'Ivoire"
}

###


POST {{baseUrl}}/property/disponibility
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "property": 95, 
    "guestNumber": 2, 
    "startDate": "28/08/2021", 
    "endDate": "28/08/2021"
}

###